Handle databases set via CloudFoundry VCAP_SERVICES
keycloak/keycloak-containers pull request #285
Opened 2020-09-03 13:14 UTC by dwaynebailey

* Extract credentials for a datbase names DB_VCAP_NAME
* Use grep to ensure we use existing tools on the current image without
  loading the image with a new tool like jq.
* DB_VENDOR is still set externally so that the script doesn't have to
  guess it correctly

Sorry haven't quite followed the guidelines on contributing.  Just wanted to push an initial PR for comment about my approach.

2020-09-03 13:19 UTC, stianst commented
I'm not too keen on adding CloudFoundry specific things to the container image. Is this something that images on Docker Hub / Quay.io supports? If so please point to other popular images that support this.

Also, please provide some more details on what the use-case is here.

2020-09-03 13:32 UTC, dwaynebailey commented
I don't use docker images much on CloudFoundry so not 100% sure how others have approached this.

ito use case, this is an outline of the issue.

In CloudFoundry I will:
1. create a DB
2. create an app manifest that specifies that the app has access to the named DB
3. Deploy the app
4. At deployment time the binding between app and DB occurs and the database credential are exposed in the `VCAP_SERVICES` environment variable from where they can be extracted by the app.

Summary is this.  I don't have the settings for the DB until I actually deploy the docker image as an app.

There are ways around this, which I currently do, which is to:
1. Create the DB
2. Create a fake empty docker app
3. Bind the two
4. Extract the DB credentials
5. Redeploy the docker app with the DB credentials that we now know.

This makes deployment a lot more complicated ito manual processes or automation.  And has a few gotchas when I'm doing deployments via Terraform.

Trust that helps.

2020-09-07 08:33 UTC, slaskawi commented
@dwaynebailey Could you please double check the documentation to see if there's any way to perform from `VCAP_SERVICES` env. variable to some others? I believe there should be a way to do that (I would will be very surprised if there's none).

2020-09-15 11:33 UTC, slaskawi commented
@dwaynebailey May I ask you to look at my previous comment?

2020-09-15 19:09 UTC, dwaynebailey commented
@slaskawi do you mean that some other env variables contain the data you'd find in `VCAP_SERVICES`? Simple answer would be no the connection data is only in that variable.   `VCAP_SERVICES` is a way to convey credentials for many types of bound services, not just a database see https://docs.cloudfoundry.org/devguide/deploy-apps/environment-variable.html#VCAP-SERVICES

2020-09-18 06:15 UTC, stianst requested changes
I'm not in favour of adding this as it is bespoke to CloudFoundry. We also have no way of testing/verifying if this actually works.

If you can show similar features added to other containers, then we may reconsider, but in general we won't add CloudFoundry specfic capabilities to the container.

Another option is of course to extend the image perhaps.

2020-09-22 08:40 UTC, slaskawi commented
I agree with @stianst here. 

Let me close it for now. @dwaynebailey if you find a generic solution how other community projects deal with it, I'm happy to reconsider.

2020-09-22 08:40 UTC, closed without merging