set default web context from env var
keycloak/keycloak-containers pull request #328
Opened 2021-10-04 14:28 UTC by m0s1x

change the default web context simply by setting the KEYCLOAK_WEB_CONTEXT environment variable

2021-10-04 15:01 UTC, stianst requested changes

2021-10-04 15:01 UTC, stianst commented on server/tools/docker-entrypoint.sh
> +
We don't modify the XML files directly like this, for maintenance reasons this has to be done with jboss-cli scripts I'm afraid.

2021-10-04 18:44 UTC, m0s1x commented on server-x/tools/docker-entrypoint.sh
> +
excuse me. i didn't know keycloak.x before.
i'll move my project to it and remove my wrong fork. thanks a lot

2021-10-05 13:12 UTC, closed without merging

2021-10-05 13:13 UTC, m0s1x commented
changes not needed

2021-10-05 13:26 UTC, stianst commented
Great, thanks for the update and closing the issue.